<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="movies.aspx.cs" Inherits="WebApplication1.movies" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
            color: #800000;
        }
        .auto-style2 {
            height: 74px;
        }
        .auto-style3 {
            height: 306px;
        }
        .auto-style4 {
            height: 74px;
            width: 571px;
            text-align: center;
        }
        .auto-style7 {
            font-size: xx-large;
            color: #FFFFFF;
            text-align: center;
            height: 165px;
        }
        .auto-style8 {
            text-align: left;
        }
        .auto-style9 {
            text-decoration: underline;
        }
        .auto-style10 {
            text-align: left;
            text-decoration: underline;
        }
        .auto-style11 {
            font-size: medium;
        }
        .auto-style12 {
            height: 74px;
            width: 519px;
        }
        .auto-style13 {
            height: 306px;
            width: 519px;
        }
        .auto-style14 {
            width: 519px;
        }
        .auto-style15 {
            font-size: 70px;
        }
        .auto-style16 {
            height: 306px;
            width: 571px;
        }
        .auto-style17 {
            width: 571px;
            color: #000000;
        }
        .auto-style19 {
            margin-left: 0px;
        }
        .auto-style20 {
            color: #FFFFFF;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="auto-style7" style="background-color: #0066b2">
            <br />
            <strong><em><span class="auto-style15">welcome to our world!</span></em></strong></div>
        <table class="auto-style1" style="background-color: #FFFFFF">
            <tr>
                <td class="auto-style4" style="background-color: #FFFFFF">
                    <div class="auto-style8">
                    <asp:Image ID="Image1" runat="server" Width="454px" ImageUrl="~/img/61a8aa2ab46181bf5de774d4246b7229.jpg" />
                        <br />
                        <span class="auto-style11" style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span class="auto-style9">The rise of Arthur Fleck, from aspiring stand-up comedian and pariah to Gotham&#39;s clown prince and leader of the revolution.</span><br class="auto-style9" />
                    </div>
                    </span><span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
                    <div class="auto-style11" data-testid="rating-button__aggregate-rating" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; -webkit-box-align: center; align-items: center; color: rgb(0, 0, 0); letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="auto-style10" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: var(--ipt-on-base-color,rgb(0,0,0)); white-space: nowrap; text-transform: none; display: flex;">
                            IMDb RATING</div>
                        <div class="sc-f056af46-3 dIcfPO" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center;">
                            <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                                <div class="auto-style8" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                    <span class="auto-style9" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">8.4</span><span class="auto-style9" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                            </div>
                        </div>
                    </div>
                    </span>
                </td>
                <td class="auto-style12" style="background-color: #FFFFFF">
                    <asp:Image ID="Image2" runat="server" Width="443px" CssClass="auto-style19" ImageUrl="~/img/8a5d441931bb7f78ebf38e839c040b55.jpg" />
                    <br />
                    <span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Based on Disneyland&#39;s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.<br />
                    <div class="sc-f056af46-1 daocKE" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: rgb(0, 0, 0); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="sc-f056af46-3 dIcfPO" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; color: rgb(0, 0, 0); letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-f056af46-4 crJaVt" style="box-sizing: border-box; margin: 0px 0.25rem 0px 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; height: 2rem; width: 2rem;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">6.6</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
                <td class="auto-style2" style="background-color: #FFFFFF">
                    <asp:Image ID="Image3" runat="server" Width="468px" CssClass="auto-style19" ImageUrl="~/img/98f13bb904cc6af14583fb83060ed672.jpg" />
                    <br />
                    <span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Fueled by his restored faith in humanity and inspired by Superman&#39;s selfless act, Bruce Wayne enlists the help of his new-found ally, Diana Prince, to face an even greater enemy.<br />
                    <div class="sc-f056af46-1 daocKE" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: rgb(0, 0, 0); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="sc-f056af46-3 dIcfPO" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; color: rgb(0, 0, 0); letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">6.1</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
            </tr>
            <tr>
                <td class="auto-style16" style="background-color: #FFFFFF">
                    <asp:Image ID="Image4" runat="server" Width="449px" ImageUrl="~/img/ed1e1a918e2f14dab18e74781d98aed4.jpg" />
                    <br />
                    <span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.<div class="sc-f056af46-1 daocKE" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: rgb(0, 0, 0); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="sc-f056af46-3 dIcfPO" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; color: rgb(0, 0, 0); letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">8.7</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
                <td class="auto-style13" style="background-color: #FFFFFF">
                    <asp:Image ID="Image5" runat="server" Width="440px" ImageUrl="~/img/28f00cff911b7efb872414515e0564af.jpg" />
                    <br />
                    <span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.<br />
                    <div class="sc-f056af46-1 daocKE" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: rgb(0, 0, 0); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING<div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">6.9</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
                <td class="auto-style3" style="background-color: #999999">
                    <asp:Image ID="Image6" runat="server" Width="465px" ImageUrl="~/img/5062195424b97d4776eda72457ee59bd.jpg" />
                    <br />
                    <span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na&#39;vi race to protect their home.<br />
                    <br />
                    <div class="sc-f056af46-1 daocKE" style="box-sizing: border-box; margin: 0px 0px 0.25rem; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); color: rgb(0, 0, 0); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="sc-f056af46-3 dIcfPO" style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; color: rgb(0, 0, 0); letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">7.7</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
            </tr>
            <tr>
                <td class="auto-style17" style="background-color: #FFFFFF">
                    <span class="auto-style20">
                    <asp:Image ID="Image7" runat="server" Width="452px" ImageUrl="~/img/558590bffb31f6b0be870ff9a46e2cbb.jpg" />
                    <br />
                    </span><span class="auto-style20" style="font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom. Granted one wish, Merida must rely on her bravery and her archery skills to undo a beastly curse.<br />
                    </span><span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
                    <div style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="auto-style20" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; margin: 0px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">7.1</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
                <td class="auto-style14" style="background-color: #FFFFFF">
                    <span class="auto-style20">
                    <asp:Image ID="Image8" runat="server" Width="441px" ImageUrl="~/img/93ff76827d42f5198710638c0263c44c.jpg" />
                    <br />
                    </span><span class="auto-style20" style="font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">A vengeful fairy is driven to curse an infant princess, only to discover that the child may be the one person who can restore peace to their troubled land.<br />
                    </span><span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
                    <div style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="auto-style20" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; margin: 0px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">6.9</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
                <td style="background-color: #FFFFFF">
                    <span class="auto-style20">
                    <asp:Image ID="Image9" runat="server" Width="464px" ImageUrl="~/img/c347a82982cb4422ff3b107c0f052cb5.jpg" />
                    <br />
                    </span><span class="auto-style20" style="font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.<br />
                    </span><span style="color: rgb(255, 255, 255); font-family: Roboto, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(31, 31, 31); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
                    <div style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: var(--ipt-type-overline-weight,600); font-stretch: inherit; font-size: var(--ipt-type-overline-size,.75rem); line-height: var(--ipt-type-overline-lineHeight,1rem); font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-overline-letterSpacing,.16667em); white-space: nowrap; text-transform: none; display: flex; orphans: 2; text-align: start; text-indent: 0px; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        IMDb RATING</div>
                    <div class="auto-style20" style="border-style: none; border-color: inherit; border-width: 0px; box-sizing: border-box; margin: 0px; padding: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Roboto, Helvetica, Arial, sans-serif; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; display: flex; -webkit-box-align: center; align-items: center; letter-spacing: 0.5px; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div class="sc-5931bdee-0 jtILVy" style="box-sizing: border-box; margin: 0px; padding: 0px 0.25rem 0px 0px; border: 0px; font: inherit; vertical-align: baseline; display: inline-flex; flex-direction: column; align-items: flex-start;">
                            <div class="sc-5931bdee-2 fdOlOf" data-testid="rating-button__aggregate-rating__score" style="box-sizing: border-box; margin: 0px 0px -0.125rem; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-body-weight,400); font-stretch: inherit; font-size: var(--ipt-type-body-size,1rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-textSecondary-color,rgba(0,0,0,0.54)); display: flex; -webkit-box-align: center; align-items: center; letter-spacing: var(--ipt-type-body-letterSpacing,.03125em); text-transform: var(--ipt-type-body-textTransform,none);">
                                <span class="sc-5931bdee-1 jUnWeS" style="box-sizing: border-box; margin: 0px; padding: 0px 0.125rem 0px 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: var(--ipt-type-headline6-weight,600); font-stretch: inherit; font-size: var(--ipt-type-headline6-size,1.25rem); line-height: 1.5rem; font-family: var(--ipt-font-family); font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; vertical-align: baseline; color: var(--ipt-on-base-color,rgb(0,0,0)); -webkit-font-smoothing: antialiased; letter-spacing: var(--ipt-type-headline6-letterSpacing,.0125em); text-transform: var(--ipt-type-headline6-textTransform,none);">6.8</span><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">/10</span></div>
                        </div>
                    </div>
                    </span>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
